### ISSUE TITLE
Citizenship -> Dual/Multiple -> Country of citizenship

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1666]
1. We're asking for comments here if necessary, but there's nowhere to leave them. I'm not sure if it's ok to add a random comment box, but either the verbiage should reflect reality (no comment box), or we should have a comment box if we're telling them they can leave one.

2. The error language talks about the country where you were born. This question is about citizenship, not place of birth. I suspect that might be sprinkled a few different places.

<img width="661" alt="screen shot 2017-07-31 at 3 37 23 pm" src="https://user-images.githubusercontent.com/5091167/28799665-c25dcaf0-7606-11e7-8e64-a1a2c2a4638b.png">

**Comment by bmallred** [comment]
Directly related to issues #1164, #1027, and #1369 in concern with the comment box.

**Comment by lauraponce** [comment]
This has been resolved: the comment call to action is now there, and the error message has been updated to:

"**This Country is not on our current list.** 
Indicate the country that currently governs the geographic location you are indicating. As necessary provide comments below to clarify."

Thoughts on modifying this error message text to be a little closer to plain language?: 

"**The country you've entered is not in our current list** 
If you don't see your country in the list, select the country that presently governs the location you are referring to. Add a comment to clarify your response." 

@billy22g @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
PR #2133

**Comment by billy22g** [comment]
This doesn't appear to be up on staging yet, but it's 💯

**Comment by billy22g** [comment]
@bmallred Still seeing the old verbiage. Not sure if this actually got deployed to staging.

**Comment by bmallred** [comment]
Looks like #2133 only modified one instance of the text and missed two other usages. Updating now with #2168

**Comment by billy22g** [comment]
@bmallred Can you close this again when these are deployed please?

**Comment by billy22g** [comment]
Still seeing this in staging @bmallred @floresj 

<img width="1134" alt="screen shot 2017-11-07 at 7 56 59 am" src="https://user-images.githubusercontent.com/5091167/32499983-4a7bab64-c391-11e7-8189-4eb40a158dab.png">

**Comment by billy22g** [comment]
LGTM now. Thanks!
